### ISSUE TITLE
Update Github link to point directly at our `marketing` repo

### ISSUE THREAD

**Issue by croz1007** [columbus-elixir/marketing#101]
We should have our Github link take visitors directly to our `marketing` repo and not to the Columbus Elixir org. Since we have issues to work in here we would want to get them here more directly.

New link should be: `https://github.com/columbus-elixir/marketing`

**Comment by freqn** [comment]
PR opened - https://github.com/columbus-elixir/marketing/pull/108

**Comment by croz1007** [comment]
Completed on PR108
