### ISSUE TITLE
Slack / Slack request?

### ISSUE THREAD

**Issue by ghost** [columbus-elixir/marketing#19]
Do we have a slack channel?  Do we need to set one up?  Should we have requesting to join the slack team be part of this app or it's own app?

Opening this for a discussion, as I'm not sure where it should go in the short term.

**Comment by mdarby** [comment]
We do -- whats a good email?

**Comment by ghost** [comment]
assuming you mean for an invite?

**Comment by mdarby** [comment]
yes, for a Slack invite :)

**Comment by ghost** [comment]
Sent you an email from said email
