### ISSUE TITLE
Add Uberauth for adding Speakers/Meetings

### ISSUE THREAD

**Issue by croz1007** [columbus-elixir/marketing#25]
Currently we are using basic auth to block access to certain actions for speakers pages, but as we get more features added to the site we will need to have a bit more ability to lock down pages, actions, and maybe sections of pages based on maybe roles and such. 

We will want to implement UberAuth to expand our options of site authorizations. and taking suggestions for solution to handle better access of things with roles.

**Comment by mdarby** [comment]
Working on this now.
