### ISSUE TITLE
Past Speakers List

### ISSUE THREAD

**Issue by croz1007** [columbus-elixir/marketing#58]
We need to be able to provide a "Past Talks" page that lists out the talks given at past events. This could be leveraged from the `/speakers` page, but the "New Speaker" link would need to be hidden unless a person is an admin. 

- [ ] Talks should grouped by meeting and ordered from most recent meetup to the oldest. 
- [ ] All links should work and open in a new tab
- [ ] Styling could be the same as how they are presented on the homepage (using gravatar, links, and info)

**Comment by Kartstig** [comment]
Closed by https://github.com/columbus-elixir/marketing/pull/62
